# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807057a388a648ea3a374081c84d965875defa7382fbd98091b5e166e4bb1c2af01bfa4a620f6032a6a142aa414ec1991f820eadedb79fcee185c4fd6ec0dfc6

test:
  secret_key_base: 62ea739e94d0008cecce0668de0b7bf4169e9850e679f254b7da6bec83899ebc0207976e4ed5f7756c72f255b30f2b163b19a6f28718b3cb585e2a57ab8964ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
